Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Style/SignalException:
  EnforcedStyle: only_raise

Style/RedundantSelf:
  Enabled: false
